apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: vault-database
  namespace: sscsi-test
spec:
  parameters:
    objects: |
      - objectName: "db-password"
        secretPath: "secret/data/db-pass"
        secretKey: "password"
    roleName: database
    vaultAddress: 'http://vault.vault.svc:8200'
    vaultSkipTLSVerify: 'true'
  provider: vault
