apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: aws-secret-manager-sts
  namespace: eso-test
  labels:
    app: external-secrets-operator
spec:
  provider:
    aws:
      auth:
      region: ap-southeast-1
      service: SecretsManager
      auth:
        jwt:
          serviceAccountRef:
            name: my-serviceaccount