apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: aws-secret-manager
  labels:
    app: external-secrets-operator
spec:
  provider:
    aws:
      auth:
        secretRef:
          accessKeyIDSecretRef:
            key: access-key
            name: awssm-secret
          secretAccessKeySecretRef:
            key: secret-access-key
            name: awssm-secret
      region: ap-southeast-1
      service: SecretsManager
