apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vault-secret-1
  namespace: eso-test
  labels:
    app: external-secrets-operator
spec:
  dataFrom:
    - extract:
        conversionStrategy: Default
        decodingStrategy: None
        key: firstsecret
        metadataPolicy: None
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: vault-secretstore
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: vault-secret-1
