kind: Secret
apiVersion: v1
metadata:
  name: tempostack-s3
  namespace: tempo
stringData:
  endpoint: https://s3.ap-southeast-1.amazonaws.com
  bucket: tempostack-cluster-5774j
  access_key_id: AAAAA
  access_key_secret: BBBBB
type: Opaque
