apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  annotations:
    instrumentation.opentelemetry.io/default-auto-instrumentation-apache-httpd-image: 'ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-apache-httpd:1.0.4'
    instrumentation.opentelemetry.io/default-auto-instrumentation-dotnet-image: 'ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-dotnet:1.15.0'
    instrumentation.opentelemetry.io/default-auto-instrumentation-go-image: 'ghcr.io/open-telemetry/opentelemetry-go-instrumentation/autoinstrumentation-go:v0.24.0'
    instrumentation.opentelemetry.io/default-auto-instrumentation-java-image: 'ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-java:2.28.1'
    instrumentation.opentelemetry.io/default-auto-instrumentation-nginx-image: 'ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-apache-httpd:1.0.4'
    instrumentation.opentelemetry.io/default-auto-instrumentation-nodejs-image: 'ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-nodejs:0.76.0'
    instrumentation.opentelemetry.io/default-auto-instrumentation-python-image: 'ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-python:0.63b1'
  name: instrumentation
  namespace: tracing-demo
spec:
  exporter:
    endpoint: 'http://otel-collector-headless.otel.svc.cluster.local:4317'
  java:
    image: 'ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-java:2.28.1'
    resources:
      limits:
        cpu: 500m
        memory: 256Mi
      requests:
        cpu: 50m
        memory: 64Mi
    volumeClaimTemplate:
      metadata: {}
      spec:
        resources: {}
  sampler:
    type: always_on
  go:
    image: 'ghcr.io/open-telemetry/opentelemetry-go-instrumentation/autoinstrumentation-go:v0.24.0'
    resourceRequirements:
      limits:
        cpu: 500m
        memory: 256Mi
      requests:
        cpu: 50m
        memory: 64Mi
    volumeClaimTemplate:
      metadata: {}
      spec:
        resources: {}
    env:
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: http://otel-collector.otel.svc.cluster.local:4318
      - name: OTEL_LOG_LEVEL
        value: debug
  nodejs:
    image: 'ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-nodejs:0.76.0'
    resourceRequirements:
      limits:
        cpu: 500m
        memory: 256Mi
      requests:
        cpu: 50m
        memory: 128Mi
    volumeClaimTemplate:
      metadata: {}
      spec:
        resources: {}
  resource: {}
  apacheHttpd:
    configPath: /usr/local/apache2/conf
    image: 'ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-apache-httpd:1.0.4'
    resourceRequirements:
      limits:
        cpu: 500m
        memory: 256Mi
      requests:
        cpu: 1m
        memory: 128Mi
    version: '2.4'
    volumeClaimTemplate:
      metadata: {}
      spec:
        resources: {}
  defaults: {}
  dotnet:
    image: 'ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-dotnet:1.15.0'
    resourceRequirements:
      limits:
        cpu: 500m
        memory: 256Mi
      requests:
        cpu: 50m
        memory: 128Mi
    volumeClaimTemplate:
      metadata: {}
      spec:
        resources: {}
  nginx:
    configFile: /etc/nginx/nginx.conf
    image: 'ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-apache-httpd:1.0.4'
    resourceRequirements:
      limits:
        cpu: 500m
        memory: 256Mi
      requests:
        cpu: 1m
        memory: 128Mi
    volumeClaimTemplate:
      metadata: {}
      spec:
        resources: {}
  python:
    image: 'ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-python:0.63b1'
    resourceRequirements:
      limits:
        cpu: 500m
        memory: 256Mi
      requests:
        cpu: 50m
        memory: 64Mi
    volumeClaimTemplate:
      metadata: {}
      spec:
        resources: {}
    env:
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: http://otel-collector.otel.svc.cluster.local:4318
      - name: OTEL_LOG_LEVEL
        value: debug