kind: Secret
apiVersion: v1
metadata:
  name: quay-demo-config
  namespace: registry
type: Opaque
stringData:
  config.yaml: |
    DISTRIBUTED_STORAGE_CONFIG:
      aws_s3_storage:  # Unique storage ID (arbitrary name)
        - S3Storage
        - s3_access_key: "YOUR_ACCESS_KEY"
          s3_secret_key: "YOUR_SECRET_KEY"
          s3_bucket: "your-quay-bucket-name"
          storage_path: "/datastorage"
          host: "s3.amazonaws.com"  # Use regional endpoint if applicable
    DISTRIBUTED_STORAGE_DEFAULT_LOCATIONS: []
    DISTRIBUTED_STORAGE_PREFERENCE:
      - aws_s3_storage
    FEATURE_SUPERUSERS_FULL_ACCESS: true
    SUPER_USERS: # The list of users you would like to grant superuser permission.
      - quayadmin


