kind: Secret
apiVersion: v1
metadata:
  name: quay-demo-config
  namespace: registry
type: Opaque
stringData:
  config.yaml: |
    DISTRIBUTED_STORAGE_CONFIG:
      rhocsStorage:
        - RHOCSStorage
        - access_key: <access_key_here>
          secret_key: <secret_key_here>
          bucket_name: <bucket_name>
          hostname: <hostname>
          is_secure: 'true'
          port: '443'
          storage_path: /datastorage/registry
          maximum_chunk_size_mb: 100 
          server_side_assembly: true 
    DISTRIBUTED_STORAGE_PREFERENCE:
      - rhocsStorage
    DISTRIBUTED_STORAGE_DEFAULT_LOCATIONS: []
    FEATURE_SUPERUSERS_FULL_ACCESS: true
    SUPER_USERS: # The list of users you would like to grant superuser permission.
      - quayadmin


