apiVersion: kiali.io/v1alpha1
kind: Kiali
metadata:
  name: kiali
  namespace: istio-system
spec:
  login_token:
    expiration_seconds: 86400
  server:
    audit_log: true
    port: 20001
    observability:
      metrics:
        enabled: true
        port: 9090
      tracing:
        collector_type: otel
        collector_url: 'jaeger-collector.istio-system:4318'
        enabled: false
        otel:
          protocol: http
          skip_verify: false
          tls_enabled: false
        sampling_rate: 0.5
    write_timeout: 60s
    require_auth: false
    profiler:
      enabled: false
    web_history_mode: browser
    cors_allow_all: false
    gzip_enabled: true
  health_config:
    compute:
      duration: 5m
      refresh_interval: 3m
      timeout: 10m
  deployment:
    network_policy:
      enabled: true
    probes:
      liveness:
        initial_delay_seconds: 5
        period_seconds: 30
      readiness:
        initial_delay_seconds: 5
        period_seconds: 30
      startup:
        failure_threshold: 6
        initial_delay_seconds: 30
        period_seconds: 10
    remote_cluster_resources_only: false
    image_digest: ''
    image_pull_policy: IfNotPresent
    cluster_wide_access: true
    logger:
      log_format: text
      log_level: debug
      sampler_rate: '1'
      time_field_format: '2006-01-02T15:04:05Z07:00'
    ingress:
      class_name: nginx
    instance_name: kiali
    secret_name: kiali
    replicas: 1
    view_only_mode: false
  auth:
    openid:
      api_token: id_token
      authentication_timeout: 300
      disable_rbac: false
      insecure_skip_verify_tls: false
      username_claim: sub
    openshift:
      insecure_skip_verify_tls: false
  clustering:
    autodetect_secrets:
      enabled: true
      label: kiali.io/multiCluster=true
    enable_exec_provider: false
    ignore_home_cluster: false
  istio_labels:
    egress_gateway_label: istio=egressgateway
    ingress_gateway_label: istio=ingressgateway
    injection_label_name: istio-injection
    injection_label_rev: istio.io/rev
  chat_ai:
    enabled: false
    store_config:
      enabled: true
      max_cache_memory_mb: 1024
      reduce_threshold: 15
      reduce_with_ai: false
  external_services:
    custom_dashboards:
      discovery_auto_threshold: 10
      discovery_enabled: auto
      enabled: true
      is_core: false
      namespace_label: namespace
      prometheus:
        auth:
          insecure_skip_verify: false
          type: none
          use_kiali_token: false
        cache_duration: 7
        cache_enabled: true
        cache_expiration: 300
        is_core: true
        thanos_proxy:
          enabled: false
          retention_period: 7d
          scrape_interval: 30s
    grafana:
      auth:
        insecure_skip_verify: false
        type: none
        use_kiali_token: false
      enabled: false
      internal_url: 'http://grafana.istio-system:3000'
      is_core: false
    istio:
      istio_sidecar_annotation: sidecar.istio.io/status
      istio_injection_annotation: sidecar.istio.io/inject
      istiod_polling_interval_seconds: 20
      envoy_admin_local_port: 15000
      istio_api_enabled: true
      istiod_pod_monitoring_port: 15014
      component_status:
        enabled: true
      istio_identity_domain: svc.cluster.local
      validation_reconcile_interval: 1m
      validation_change_detection_enabled: true
    perses:
      auth:
        insecure_skip_verify: false
        type: none
        use_kiali_token: false
      dashboards:
       - name: Istio Service Dashboard
         variables:
           datasource: var-datasource
           namespace: var-namespace
           service: var-service
           version: var-version
       - name: Istio Workload Dashboard
         variables:
           datasource: var-datasource
           namespace: var-namespace
           version: var-version
           workload: var-workload
       - name: "Istio Mesh Dashboard"
         variables:
           namespace: "var-namespace"
           workload: "var-workload"
           datasource: "var-datasource"
       - name: "Istio Ztunnel Dashboard"
         variables:
           namespace: "var-namespace"
           workload: "var-workload"
      enabled: true
      is_core: false
      project: istio
      url_format: openshift
      project: perses-dev
      external_url: "https://console-openshift-console.apps.cluster-m6jjv.m6jjv.sandbox5299.opentlc.com"
    prometheus:
      auth:
        insecure_skip_verify: true
        type: bearer
        use_kiali_token: true
      cache_duration: 7
      cache_enabled: true
      cache_expiration: 300
      is_core: true
      thanos_proxy:
        enabled: true
      url: https://thanos-querier.openshift-monitoring.svc.cluster.local:9091
    tracing:
      enabled: false
      grpc_port: 9095
      namespace_selector: true
      tempo_config:
        cache_capacity: 200
        cache_enabled: true
        url_format: grafana
      auth:
        insecure_skip_verify: false
        type: none
        use_kiali_token: false
      query_timeout: 5
      disable_version_check: false
      provider: jaeger
      use_waypoint_name: false
      is_core: false
      use_grpc: true
  version: default
  kubernetes_config:
    burst: 200
    cache_duration: 300
    cache_token_namespace_duration: 10
    qps: 175
  kiali_feature_flags:
    clustering:
      enable_exec_provider: false
    istio_annotation_action: true
    istio_injection_action: true
    istio_upgrade_action: false
    ui_defaults:
      graph:
        settings:
          animation: point
        traffic:
          ambient: total
          grpc: requests
          http: requests
          tcp: sent
      i18n:
        show_selector: false
      list:
        include_health: true
        include_istio_resources: true
        include_validations: true
        show_include_toggles: false
      metrics_per_refresh: 1m
      refresh_interval: 1m
      tracing:
        limit: 100
    validations:
      skip_wildcard_gateway_hosts: false
