kind: Deployment
apiVersion: apps/v1
metadata:
  name: httpd
  namespace: cert-offload
spec:
  replicas: 3
  selector:
    matchLabels:
      app: httpd
  template:
    metadata:
      labels:
        app: httpd
    spec:
      volumes:
        - name: httpd-config
          configMap:
            name: httpd-config
            defaultMode: 420
      containers:
        - name: httpd
          image: 'registry.redhat.io/rhel8/httpd-24:latest'
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources: {}
          volumeMounts:
            - name: httpd-config
              mountPath: /etc/httpd/conf.d/cert-offload.conf
              subPath: cert-offload.conf
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
