kind: ConfigMap
apiVersion: v1
metadata:
  name: httpd-config
  namespace: cert-offload
immutable: false
data:
  cert-offload.conf: |-
    LoadModule proxy_module modules/mod_proxy.so
    LoadModule proxy_http_module modules/mod_proxy_http.so
    LoadModule proxy_connect_module modules/mod_proxy_connect.so
    LoadModule ssl_module modules/mod_ssl.so
    <VirtualHost *:8080>
        ServerName httpd.cert-offload.svc

        LogLevel debug proxy:trace5
        LogFormat "%h %l %u %t \"%r\" %>s %b \"%{Authorization}i\" \"%{Host}i\"" proxy_debug
        CustomLog /var/log/httpd/proxy_access.log proxy_debug

        # Enable forward proxy
        ProxyRequests On
        ProxyVia On

        # Enable SSL for outbound connections to upstream
        SSLProxyEngine On

        # Verify upstream server's certificate (recommended)
        SSLProxyVerify none
        SSLProxyCheckPeerCN off
        SSLProxyCheckPeerName off
        SSLProxyCheckPeerExpire off

        #ProxyPreserveHost Off
        #RequestHeader set Host "s3.openshift-storage.svc"
        ProxyPreserveHost On

        # Upgrade outbound requests to HTTPS
        ProxyPass / https://s3.openshift-storage.svc/
        ProxyPassReverse / https://s3.openshift-storage.svc/

        # Rewrite HTTP → HTTPS for the proxy target
        RequestHeader set X-Forwarded-Proto "https"

    </VirtualHost>
