apiVersion: v1
stringData:
  access_key_id: abcdef123456
  access_key_secret: asdfghjkkll/1d
  bucketnames: lokistack-bucket
  endpoint: http://httpd.cert-offload.svc:8080
  forcepathstyle: true
  region: us-east-1
kind: Secret
metadata:
  name: logging-loki-s3
  namespace: openshift-logging
type: Opaque