apiVersion: v1
kind: Namespace
metadata:
  name: open-cluster-management-clusterset1-set
spec:
  finalizers:
  - kubernetes
---
apiVersion: cluster.open-cluster-management.io/v1beta2
kind: ManagedClusterSetBinding
metadata:
  namespace: open-cluster-management-clusterset1-set
  name: clusterset1
spec:
  clusterSet: clusterset1
---
apiVersion: cluster.open-cluster-management.io/v1beta2
kind: ManagedClusterSet
metadata:
  name: clusterset1
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: clusterrole1
rules:
  - apiGroups: ["cluster.open-cluster-management.io"]
    resources: ["managedclustersets/join"]
    resourceNames: ["clusterset1"]
    verbs: ["create"]
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: clusterset1
  namespace: open-cluster-management-clusterset1-set
spec:
  clusterSets:
  - clusterset1
  decisionStrategy:
    groupStrategy:
      clustersPerDecisionGroup: 0
  prioritizerPolicy:
    mode: Additive
  spreadPolicy: {}
  tolerations:
  - key: cluster.open-cluster-management.io/unreachable
    operator: Equal
  - key: cluster.open-cluster-management.io/unavailable
    operator: Equal