apiVersion: v1
kind: Secret
metadata:
  name: aws-creds
type: Opaque
stringData:
  # Use keys as expected by the provider (e.g., "accessKeyID", "secretAccessKey")
  accessKeyID: "YOUR_ACCESS_KEY_ID"
  secretAccessKey: "YOUR_SECRET_ACCESS_KEY"