apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fake-failing-pvc
  namespace: quay-enterprise
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: non-existent-storage-class
  volumeMode: Filesystem