apiVersion: apps/v1
kind: Deployment
metadata:
  name: tsc-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tsc-demo
  template:
    metadata:
      labels:
        app: tsc-demo
    spec:
      containers:
      - name: hello-openshift
        image: openshift/hello-openshift:latest
        ports:
        - containerPort: 80
      topologySpreadConstraints:
          - maxSkew: 1
            topologyKey: topology.kubernetes.io/zone
            whenUnsatisfiable: ScheduleAnyway
            labelSelector:
              matchLabels:
                app: tsc-demo