apiVersion: gateway.networking.k8s.io/v1
kind: GRPCRoute
metadata:
  name: greeter-server
  namespace: gwapi-test
spec:
  parentRefs:
  - name: default-gateway
  hostnames:
  - "gateway.greeter.${CLUSTER_NAME}"
  rules:
  - backendRefs:
    - name: greeter-server
      port: 50051
